name: dart_application_1
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies: {basic_utils: ^5.1.2, crypto: ^3.0.2, crypto_keys: ^0.3.0, cryptography: ^2.0.5, pointycastle: ^3.6.1}
